import { Quattrocento_Sans } from "next/font/google";
import "./globals.css";

const quattrocentoSans = Quattrocento_Sans({
  variable: "--font-quattrocento-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${quattrocentoSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
